<?php

use App\Http\Controllers\Api\AccommodationController;
use App\Http\Controllers\Api\AnnouncementController;
use App\Http\Controllers\Api\AnnouncementNotificationController;
use App\Http\Controllers\Api\Admin\AccommodationController as AdminAccommodationController;
use App\Http\Controllers\Api\Admin\AmenityController as AdminAmenityController;
use App\Http\Controllers\Api\Admin\AnnouncementController as AdminAnnouncementController;
use App\Http\Controllers\Api\Admin\AttendanceRecordController as AdminAttendanceRecordController;
use App\Http\Controllers\Api\Iot\FingerprintAttendanceController;
use App\Http\Controllers\Api\Admin\EmployeeController as AdminEmployeeController;
use App\Http\Controllers\Api\Admin\DashboardController;
use App\Http\Controllers\Api\Admin\HousekeepingTaskController as AdminHousekeepingTaskController;
use App\Http\Controllers\Api\Admin\InventoryAssetController as AdminInventoryAssetController;
use App\Http\Controllers\Api\Admin\InventoryStockController as AdminInventoryStockController;
use App\Http\Controllers\Api\Admin\ReportController as AdminReportController;
use App\Http\Controllers\Api\Admin\ReservationController as AdminReservationController;
use App\Http\Controllers\Api\Admin\SettingController as AdminSettingController;
use App\Http\Controllers\Api\Admin\SystemLogController as AdminSystemLogController;
use App\Http\Controllers\Api\Admin\GlobalSearchController as AdminGlobalSearchController;
use App\Http\Controllers\Api\Admin\UserController as AdminUserController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\Chat\ConversationController as ChatConversationController;
use App\Http\Controllers\Api\FrontDesk\ReservationController as FrontDeskReservationController;
use App\Http\Controllers\Api\FrontDesk\PaymentController as FrontDeskPaymentController;
use App\Http\Controllers\Api\FrontDesk\AccommodationController as FrontDeskAccommodationController;
use App\Http\Controllers\Api\FrontDesk\AnnouncementController as FrontDeskAnnouncementController;
use App\Http\Controllers\Api\FrontDesk\DashboardController as FrontDeskDashboardController;
use App\Http\Controllers\Api\FrontDesk\BookingQrController as FrontDeskBookingQrController;
use App\Http\Controllers\Api\Manager\OperationalController as ManagerOperationalController;
use App\Http\Controllers\Api\PublicSettingController;
use App\Http\Controllers\Api\ReservationController;
use App\Http\Controllers\Api\GuestFeedbackController;
use Illuminate\Support\Facades\Route;

Route::get('/health', fn () => response()->json([
    'status' => 'ok',
    'service' => config('app.name'),
]));

Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:6,1');
Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:6,1');
Route::post('/email/verify-code', [AuthController::class, 'verifyEmailCode'])->middleware('throttle:10,1');
Route::post('/email/resend-code', [AuthController::class, 'resendEmailCode'])->middleware('throttle:5,1');
Route::post('/email/cancel-registration', [AuthController::class, 'cancelPendingRegistration'])->middleware('throttle:5,1');

Route::get('/accommodations', [AccommodationController::class, 'index']);
Route::get('/accommodations/{accommodation}', [AccommodationController::class, 'show']);
Route::get('/accommodations/{accommodation}/availability', [AccommodationController::class, 'availability']);
Route::post('/guest/reservations', [ReservationController::class, 'guestStore'])->middleware('throttle:10,1');
Route::post('/guest/reservations/{reservation}/abandon', [ReservationController::class, 'guestAbandon'])->middleware('throttle:10,1');
Route::post('/guest/payments/paymongo/checkout', [PaymentController::class, 'guestCheckout'])->middleware('throttle:10,1');
Route::get('/guest/payments/reservations/{reservation}/status', [PaymentController::class, 'guestPaymentStatus'])->middleware('throttle:30,1');
Route::get('/guest/booking', [PaymentController::class, 'guestBooking'])->middleware('throttle:30,1');
Route::post('/guest/booking/feedback', [GuestFeedbackController::class, 'storeGuest'])->middleware('throttle:10,1');
Route::post('/guest/booking/payments/paymongo/checkout', [PaymentController::class, 'guestBookingCheckout'])->middleware('throttle:10,1');
Route::get('/guest/booking/reservations/{reservation}/status', [PaymentController::class, 'guestBookingPaymentStatus'])->middleware('throttle:30,1');
Route::get('/announcements', [AnnouncementController::class, 'index']);
Route::get('/public-settings', [PublicSettingController::class, 'show']);
Route::post('/webhooks/paymongo', [PaymentController::class, 'webhook'])->middleware('throttle:paymongo-webhook');
Route::get('/chatbot/rules', [ChatConversationController::class, 'publicRules']);
Route::post('/chat/conversations', [ChatConversationController::class, 'start'])->middleware('throttle:20,1');
Route::get('/chat/conversations/{conversationUuid}', [ChatConversationController::class, 'show'])->middleware('throttle:40,1');
Route::post('/chat/conversations/{conversationUuid}/messages', [ChatConversationController::class, 'sendMessage'])->middleware('throttle:30,1');
Route::post('/chat/conversations/{conversationUuid}/escalate', [ChatConversationController::class, 'escalate'])->middleware('throttle:10,1');

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user', [AuthController::class, 'user']);
    Route::get('/notifications/announcements', [AnnouncementNotificationController::class, 'index']);
    Route::post('/notifications/announcements/read-all', [AnnouncementNotificationController::class, 'markAllRead']);
    Route::post('/notifications/announcements/{announcement}/read', [AnnouncementNotificationController::class, 'markRead']);
    Route::middleware('role:admin')->prefix('admin')->group(function () {
        Route::get('/dashboard-summary', [DashboardController::class, 'summary']);
        Route::get('/amenities', [AdminAmenityController::class, 'index']);
        Route::post('/amenities', [AdminAmenityController::class, 'store']);
        Route::apiResource('/accommodations', AdminAccommodationController::class);
        Route::patch('/accommodations/{accommodation}/status', [AdminAccommodationController::class, 'updateStatus']);
        Route::get('/reservations', [AdminReservationController::class, 'index']);
        Route::get('/reservations/{reservation}', [AdminReservationController::class, 'show']);
        Route::patch('/reservations/{reservation}/status', [AdminReservationController::class, 'updateStatus']);
        Route::post('/reservations/{reservation}/refund', [AdminReservationController::class, 'recordRefund']);
        Route::apiResource('/users', AdminUserController::class)->except(['destroy']);
        Route::patch('/users/{user}/status', [AdminUserController::class, 'updateStatus']);
        Route::patch('/users/{user}/password', [AdminUserController::class, 'resetPassword']);
        Route::apiResource('/inventory-assets', AdminInventoryAssetController::class)->except(['destroy']);
        Route::patch('/inventory-assets/{inventoryAsset}/assign', [AdminInventoryAssetController::class, 'assign']);
        Route::patch('/inventory-assets/{inventoryAsset}/condition', [AdminInventoryAssetController::class, 'updateCondition']);
        Route::patch('/inventory-assets/{inventoryAsset}/status', [AdminInventoryAssetController::class, 'updateStatus']);
        Route::get('/inventory-stock-items', [AdminInventoryStockController::class, 'index']);
        Route::post('/inventory-stock-items', [AdminInventoryStockController::class, 'store']);
        Route::get('/inventory-stock-items/movements', [AdminInventoryStockController::class, 'movements']);
        Route::get('/inventory-stock-items/{inventoryStockItem}', [AdminInventoryStockController::class, 'show']);
        Route::put('/inventory-stock-items/{inventoryStockItem}', [AdminInventoryStockController::class, 'update']);
        Route::post('/inventory-stock-items/{inventoryStockItem}/stock-in', [AdminInventoryStockController::class, 'stockIn']);
        Route::post('/inventory-stock-items/{inventoryStockItem}/stock-out', [AdminInventoryStockController::class, 'stockOut']);
        Route::apiResource('/housekeeping-tasks', AdminHousekeepingTaskController::class)->except(['destroy']);
        Route::patch('/housekeeping-tasks/{housekeepingTask}/assign', [AdminHousekeepingTaskController::class, 'assign']);
        Route::patch('/housekeeping-tasks/{housekeepingTask}/status', [AdminHousekeepingTaskController::class, 'updateStatus']);
        Route::apiResource('/employees', AdminEmployeeController::class)->except(['show']);
        Route::get('/employees/fingerprint/available-slot', [AdminEmployeeController::class, 'fingerprintSlot']);
        Route::post('/employees/{employee}/fingerprint', [AdminEmployeeController::class, 'assignFingerprint']);
        Route::delete('/employees/{employee}/fingerprint', [AdminEmployeeController::class, 'clearFingerprint']);
        Route::post('/iot/fingerprints/enroll', [\App\Http\Controllers\Api\Admin\IotBridgeController::class, 'enroll']);
        Route::post('/iot/fingerprints/delete', [\App\Http\Controllers\Api\Admin\IotBridgeController::class, 'delete']);
        Route::post('/iot/fingerprints/delete-for-employee/{employee}', [\App\Http\Controllers\Api\Admin\IotBridgeController::class, 'deleteForEmployee']);
        Route::apiResource('/attendance-records', AdminAttendanceRecordController::class)->except(['destroy']);
        Route::get('/reports', [AdminReportController::class, 'summary']);
        Route::get('/reports/export', [AdminReportController::class, 'export']);
        Route::get('/reports/export/pdf', [AdminReportController::class, 'exportPdf']);
        Route::get('/reports/export/excel', [AdminReportController::class, 'exportExcel']);
        Route::apiResource('/announcements', AdminAnnouncementController::class)->except(['destroy']);
        Route::patch('/announcements/{announcement}/status', [AdminAnnouncementController::class, 'updateStatus']);
        Route::apiResource('/system-logs', AdminSystemLogController::class)->only(['index', 'show']);
        Route::get('/global-search', AdminGlobalSearchController::class);
        Route::get('/settings', [AdminSettingController::class, 'index']);
        Route::post('/settings', [AdminSettingController::class, 'update']);
        Route::put('/settings', [AdminSettingController::class, 'update']);
        Route::get('/support/conversations', [ChatConversationController::class, 'staffIndex']);
        Route::get('/support/conversations/{conversation}', [ChatConversationController::class, 'staffShow']);
        Route::post('/support/conversations/{conversation}/claim', [ChatConversationController::class, 'claim']);
        Route::post('/support/conversations/{conversation}/messages', [ChatConversationController::class, 'staffSendMessage']);
        Route::post('/support/conversations/{conversation}/resolve', [ChatConversationController::class, 'resolve']);
        Route::get('/chatbot/categories', [ChatConversationController::class, 'adminCategories']);
        Route::get('/chatbot/rules', [ChatConversationController::class, 'adminRules']);
        Route::post('/chatbot/categories', [ChatConversationController::class, 'adminStoreCategory']);
        Route::put('/chatbot/categories/{chatbotCategory}', [ChatConversationController::class, 'adminUpdateCategory']);
        Route::delete('/chatbot/categories/{chatbotCategory}', [ChatConversationController::class, 'adminDeleteCategory']);
        Route::post('/chatbot/rules', [ChatConversationController::class, 'adminStoreRule']);
        Route::put('/chatbot/rules/{chatbotRule}', [ChatConversationController::class, 'adminUpdateRule']);
        Route::delete('/chatbot/rules/{chatbotRule}', [ChatConversationController::class, 'adminDeleteRule']);
    });
    Route::middleware('role:manager')->prefix('manager')->group(function () {
        Route::get('/dashboard-summary', [ManagerOperationalController::class, 'dashboard']);
        Route::get('/reservations', [ManagerOperationalController::class, 'reservations']);
        Route::get('/reservations/{reservation}', [ManagerOperationalController::class, 'reservation']);
        Route::patch('/reservations/{reservation}/status', [ManagerOperationalController::class, 'updateReservationStatus']);
        Route::get('/accommodations', [ManagerOperationalController::class, 'accommodations']);
        Route::get('/accommodations/{accommodation}', [ManagerOperationalController::class, 'accommodation']);
        Route::patch('/accommodations/{accommodation}/status', [ManagerOperationalController::class, 'updateAccommodationStatus']);
        Route::get('/inventory-assets', [ManagerOperationalController::class, 'inventory']);
        Route::get('/inventory-assets/{inventoryAsset}', [ManagerOperationalController::class, 'inventoryAsset']);
        Route::patch('/inventory-assets/{inventoryAsset}/condition', [ManagerOperationalController::class, 'updateInventoryCondition']);
        Route::patch('/inventory-assets/{inventoryAsset}/status', [ManagerOperationalController::class, 'updateInventoryStatus']);
        Route::get('/housekeeping-tasks', [ManagerOperationalController::class, 'housekeeping']);
        Route::post('/housekeeping-tasks', [ManagerOperationalController::class, 'createHousekeepingTask']);
        Route::get('/housekeeping-tasks/{housekeepingTask}', [ManagerOperationalController::class, 'housekeepingTask']);
        Route::put('/housekeeping-tasks/{housekeepingTask}', [ManagerOperationalController::class, 'updateHousekeepingTask']);
        Route::patch('/housekeeping-tasks/{housekeepingTask}/assign', [ManagerOperationalController::class, 'assignHousekeepingTask']);
        Route::patch('/housekeeping-tasks/{housekeepingTask}/status', [ManagerOperationalController::class, 'updateHousekeepingStatus']);
        Route::get('/attendance-records', [ManagerOperationalController::class, 'attendance']);
        Route::get('/attendance-records/{attendanceRecord}', [ManagerOperationalController::class, 'attendanceRecord']);
        Route::get('/reports', [AdminReportController::class, 'summary']);
        Route::get('/announcements', [ManagerOperationalController::class, 'announcements']);
        Route::get('/announcements/{announcement}', [ManagerOperationalController::class, 'announcement']);
        Route::get('/support/conversations', [ChatConversationController::class, 'staffIndex']);
        Route::get('/support/conversations/{conversation}', [ChatConversationController::class, 'staffShow']);
        Route::post('/support/conversations/{conversation}/claim', [ChatConversationController::class, 'claim']);
        Route::post('/support/conversations/{conversation}/messages', [ChatConversationController::class, 'staffSendMessage']);
        Route::post('/support/conversations/{conversation}/resolve', [ChatConversationController::class, 'resolve']);
    });
    Route::middleware('role:front_desk_staff')->prefix('frontdesk')->group(function () {
        Route::get('/dashboard-summary', [FrontDeskDashboardController::class, 'summary']);
        Route::get('/reservations', [FrontDeskReservationController::class, 'index']);
        Route::get('/reservations/{reservation}', [FrontDeskReservationController::class, 'show']);
        Route::patch('/reservations/{reservation}/status', [FrontDeskReservationController::class, 'updateStatus']);
        Route::post('/reservations/{reservation}/payments', [FrontDeskPaymentController::class, 'store']);
        Route::post('/booking-qr/verify', [FrontDeskBookingQrController::class, 'verify'])->middleware('throttle:30,1');
        Route::get('/accommodations', [FrontDeskAccommodationController::class, 'index']);
        Route::get('/accommodations/{accommodation}', [FrontDeskAccommodationController::class, 'show']);
        Route::get('/announcements', [FrontDeskAnnouncementController::class, 'index']);
        Route::get('/announcements/{announcement}', [FrontDeskAnnouncementController::class, 'show']);
        Route::get('/support/conversations', [ChatConversationController::class, 'staffIndex']);
        Route::get('/support/conversations/{conversation}', [ChatConversationController::class, 'staffShow']);
        Route::post('/support/conversations/{conversation}/claim', [ChatConversationController::class, 'claim']);
        Route::post('/support/conversations/{conversation}/messages', [ChatConversationController::class, 'staffSendMessage']);
        Route::post('/support/conversations/{conversation}/resolve', [ChatConversationController::class, 'resolve']);
    });
    Route::put('/user/profile', [AuthController::class, 'updateProfile'])->middleware('role:guest');
    Route::patch('/user/password', [AuthController::class, 'updatePassword'])->middleware('role:guest');
    Route::get('/reservations', [ReservationController::class, 'index'])->middleware('role:guest');
    Route::post('/reservations', [ReservationController::class, 'store'])->middleware('role:guest');
    Route::get('/reservations/{reservation}', [ReservationController::class, 'show'])->middleware('role:guest');
    Route::post('/reservations/{reservation}/cancel', [ReservationController::class, 'cancel'])->middleware('role:guest');
    Route::post('/reservations/{reservation}/feedback', [GuestFeedbackController::class, 'store'])->middleware('role:guest');
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/payments/paymongo/checkout', [PaymentController::class, 'checkout'])->middleware('role:guest');
    Route::get('/payments', [PaymentController::class, 'index'])->middleware('role:guest');
    Route::get('/payments/reservations/{reservation}', [PaymentController::class, 'show'])->middleware('role:guest');
    Route::get('/payments/reservations/{reservation}/status', [PaymentController::class, 'paymentStatus'])->middleware('role:guest');
});

Route::post('/iot/attendance/fingerprint', [FingerprintAttendanceController::class, 'store'])
    ->middleware(['iot.device', 'throttle:iot-attendance']);
