<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>DMD Resort Management Report</title>
    <style>
        @page { margin: 34px 36px 42px; }
        body { color: #26372e; font-family: DejaVu Sans, sans-serif; font-size: 9px; }
        h1 { color: #17362b; font-size: 22px; margin: 0 0 4px; }
        h2 { border-bottom: 1px solid #d7e1da; color: #245140; font-size: 13px; margin: 20px 0 8px; padding-bottom: 4px; }
        p { margin: 3px 0; }
        .muted { color: #718077; }
        .brand { color: #108b3f; font-size: 10px; font-weight: bold; letter-spacing: 1.4px; }
        .meta { border-bottom: 1px solid #d7e1da; margin: 10px 0 16px; padding-bottom: 10px; }
        .meta table, .kpis { width: 100%; }
        .meta td { padding: 2px 0; }
        .meta td:first-child { color: #718077; width: 120px; }
        .kpis td { border: 1px solid #d7e1da; padding: 9px; width: 25%; }
        .kpi-label { color: #718077; font-size: 7px; text-transform: uppercase; }
        .kpi-value { color: #17362b; font-size: 13px; font-weight: bold; margin-top: 5px; }
        table.data { border-collapse: collapse; width: 100%; }
        table.data th { background: #245140; color: #fff; font-size: 7px; padding: 6px 5px; text-align: left; }
        table.data td { border-bottom: 1px solid #e4ebe5; padding: 5px; }
        .empty { border: 1px dashed #cbd8ce; color: #718077; padding: 10px; }
        .right { text-align: right; }
        footer { bottom: -24px; color: #88958d; font-size: 7px; position: fixed; text-align: center; width: 100%; }
    </style>
</head>
<body>
    <footer>DMD Family Resort Management System · Generated {{ $generatedAt->format('M j, Y g:i A') }} · Page {PAGE_NUM} of {PAGE_COUNT}</footer>
    <div class="brand">DMD FAMILY RESORT</div>
    <h1>Management Report</h1>
    <div class="meta"><table><tr><td>Reporting Period</td><td>{{ $data['period']['label'] }}</td></tr><tr><td>Generated</td><td>{{ $generatedAt->format('F j, Y g:i A') }}</td></tr><tr><td>Generated By</td><td>{{ $generatedBy }}</td></tr></table></div>

    <h2>Executive Summary</h2>
    <table class="kpis"><tr>
        <td><div class="kpi-label">Collected Revenue</div><div class="kpi-value">₱{{ number_format((float) $data['financial']['collected_revenue'], 2) }}</div></td>
        <td><div class="kpi-label">Total Reservations</div><div class="kpi-value">{{ $data['reservations']['summary']['total'] ?? 0 }}</div></td>
        <td><div class="kpi-label">Occupancy</div><div class="kpi-value">{{ number_format((float) ($data['accommodations']['occupancy_rate'] ?? 0), 1) }}%</div></td>
        <td><div class="kpi-label">Guest Mood</div><div class="kpi-value">{{ $data['guest_mood']['mood'] ? $data['guest_mood']['mood']['label'].' '.number_format((float) $data['guest_mood']['mood_score'], 1).'%' : 'No feedback yet' }}</div></td>
    </tr></table>

    <h2>Financial Summary</h2>
    <table class="data"><tr><th>Metric</th><th class="right">Value</th></tr>
        @foreach(['Booking Value' => 'booking_value', 'Collected Revenue' => 'collected_revenue', 'Outstanding Balance' => 'outstanding_balance', 'Refunds Processed' => 'refunds_processed', 'Net Collected Revenue' => 'net_collected_revenue'] as $label => $key)
            <tr><td>{{ $label }}</td><td class="right">₱{{ number_format((float) $data['financial'][$key], 2) }}</td></tr>
        @endforeach
    </table>

    <h2>Reservation Summary</h2>
    <table class="data"><tr><th>Status</th><th class="right">Count</th></tr>
        @foreach(\App\Models\Reservation::adminStatuses() as $status)<tr><td>{{ ucwords(str_replace('_', ' ', $status)) }}</td><td class="right">{{ $data['reservations']['summary'][$status] ?? 0 }}</td></tr>@endforeach
    </table>

    <h2>Collection by Payment Source</h2>
    @if(count($data['financial']['payment_method_breakdown']))<table class="data"><tr><th>Source</th><th class="right">Amount</th></tr>@foreach($data['financial']['payment_method_breakdown'] as $source)<tr><td>{{ $source['source'] }}</td><td class="right">₱{{ number_format((float) $source['amount'], 2) }}</td></tr>@endforeach</table>@else<div class="empty">No successful collections for this reporting period.</div>@endif

    <h2>Guest Satisfaction</h2>
    @if(($data['guest_mood']['response_count'] ?? 0) > 0)
        <p><b>Mood Score:</b> {{ number_format((float) $data['guest_mood']['mood_score'], 1) }}% · <b>Average Rating:</b> {{ number_format((float) $data['guest_mood']['average_rating'], 2) }} / 5 · <b>Responses:</b> {{ $data['guest_mood']['response_count'] }}</p>
        <table class="data"><tr><th>Mood</th><th class="right">Responses</th></tr>@foreach($data['guest_mood']['distribution'] as $mood)<tr><td>{{ $mood['label'] }}</td><td class="right">{{ $mood['count'] }}</td></tr>@endforeach</table>
    @else<div class="empty">No guest feedback yet.</div>@endif

    <h2>Payment Transactions</h2>
    @if(count($data['financial']['payment_transactions']))<table class="data"><tr><th>Date</th><th>Booking</th><th>Purpose</th><th>Source</th><th>Amount</th><th>Status</th></tr>@foreach($data['financial']['payment_transactions'] as $row)<tr><td>{{ $row['payment_date'] ? \Carbon\CarbonImmutable::parse($row['payment_date'])->format('Y-m-d') : '—' }}</td><td>{{ $row['booking_reference'] }}</td><td>{{ ucwords(str_replace('_', ' ', $row['purpose'])) }}</td><td>{{ $row['source'] }}</td><td>₱{{ number_format((float) $row['amount'], 2) }}</td><td>{{ ucwords(str_replace('_', ' ', $row['status'])) }}</td></tr>@endforeach</table>@else<div class="empty">No payment transactions for this reporting period.</div>@endif

    <h2>Outstanding Balances</h2>
    @if(count($data['financial']['outstanding_balances']))<table class="data"><tr><th>Booking</th><th>Guest</th><th>Total</th><th>Paid</th><th>Outstanding</th></tr>@foreach($data['financial']['outstanding_balances'] as $row)<tr><td>{{ $row['booking_reference'] }}</td><td>{{ $row['customer'] ?? 'Guest' }}</td><td>₱{{ number_format((float) $row['booking_value'], 2) }}</td><td>₱{{ number_format((float) $row['amount_paid'], 2) }}</td><td>₱{{ number_format((float) $row['balance_due'], 2) }}</td></tr>@endforeach</table>@else<div class="empty">No outstanding balances for this reporting period.</div>@endif

    <h2>Refund Activity</h2>
    @if(count($data['financial']['refund_activity']))<table class="data"><tr><th>Date</th><th>Booking</th><th>Eligible Deposit</th><th>Refund Amount</th><th>Status</th><th>Reference</th></tr>@foreach($data['financial']['refund_activity'] as $row)<tr><td>{{ $row['date'] ? \Carbon\CarbonImmutable::parse($row['date'])->format('Y-m-d') : '—' }}</td><td>{{ $row['booking_reference'] }}</td><td>₱{{ number_format((float) $row['eligible_deposit'], 2) }}</td><td>₱{{ number_format((float) $row['refund_amount'], 2) }}</td><td>{{ ucwords(str_replace('_', ' ', $row['status'])) }}</td><td>{{ $row['reference'] ?? '—' }}</td></tr>@endforeach</table>@else<div class="empty">No processed refunds for this reporting period.</div>@endif
</body>
</html>
